# docker-example1 hello world 
# FROM alpine:latest
# MAINTAINER xbf
# CMD echo 'hello docker'
# $docker build -t hello_docker .


# docker-example2 hello world 
# FROM ubuntu
# MAINTAINER endlif
# RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list 
# RUN apt-get update
# RUN apt-get install -y nginx
# COPY index.html /var/www/html
# ENTRYPOINT [ "/usr/sbin/nginx","-g","daemon off;"]
# EXPOSE 80
# $docker build -t endlif/hello-nginx .
# $docker run -d -p 80:80 endlif/hello-nginx 
# then test curl http://localhost


docker-example3 hello world 